name: 'starting github context'
on: workflow_dispatch
jobs:
    info:
        runs-on: 'ubuntu-latest'
        steps:
            - name: 'using github action context'
              run: echo "${{ toJson(github) }}"
